public class FenetrePrincipale extends javax.swing.JFrame {

    private Partie partie;
    private javax.swing.JButton[][] boutons;
    private javax.swing.JPanel panelColonnes;
private javax.swing.JPanel panelLignes;
private javax.swing.JPanel panelBas;

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName());

    public FenetrePrincipale() {
        initComponents();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().removeAll();
getContentPane().add(panelGrille, java.awt.BorderLayout.CENTER);
panelColonnes = new javax.swing.JPanel();
panelColonnes.setLayout(new java.awt.GridLayout(1, 5));

for (int j = 0; j < 5; j++) {
    final int col = j;
    javax.swing.JButton b = new javax.swing.JButton("C" + j);
    b.addActionListener(e -> {
        partie.getGrille().activerColonneDeCellules(col);
        rafraichirGrille();
    });
    panelColonnes.add(b);
}

getContentPane().add(panelColonnes, java.awt.BorderLayout.NORTH);
panelLignes = new javax.swing.JPanel();
panelLignes.setLayout(new java.awt.GridLayout(5, 1));

for (int i = 0; i < 5; i++) {
    final int lig = i;
    javax.swing.JButton b = new javax.swing.JButton("L" + i);
    b.addActionListener(e -> {
        partie.getGrille().activerLigneDeCellules(lig);
        rafraichirGrille();
    });
    panelLignes.add(b);
}

getContentPane().add(panelLignes, java.awt.BorderLayout.WEST);
panelBas = new javax.swing.JPanel();

javax.swing.JButton btnDiagMont = new javax.swing.JButton("Diagonale ↗");
btnDiagMont.addActionListener(e -> {
    partie.getGrille().activerDiagonaleMontante();
    rafraichirGrille();
});

javax.swing.JButton btnDiagDesc = new javax.swing.JButton("Diagonale ↘");
btnDiagDesc.addActionListener(e -> {
    partie.getGrille().activerDiagonaleDescendante();
    rafraichirGrille();
});

javax.swing.JButton btnReset = new javax.swing.JButton("Recommencer");
btnReset.addActionListener(e -> {
    partie.initialiserPartie();
    rafraichirGrille();
});

panelBas.add(btnDiagMont);
panelBas.add(btnDiagDesc);
panelBas.add(btnReset);

getContentPane().add(panelBas, java.awt.BorderLayout.SOUTH);
revalidate();
repaint();





        int taille = 5;

        // 1️⃣ Initialisation du modèle
        partie = new Partie(taille, taille);
        partie.initialiserPartie();

        // 2️⃣ Création de la grille graphique
        boutons = new javax.swing.JButton[taille][taille];
        panelGrille.setLayout(new java.awt.GridLayout(taille, taille));

        for (int i = 0; i < taille; i++) {
            for (int j = 0; j < taille; j++) {
                final int ligne = i;

javax.swing.JButton b = new javax.swing.JButton();
b.addActionListener(e -> {
    partie.getGrille().activerLigneDeCellules(ligne);
    rafraichirGrille();
});

                
                boutons[i][j] = b;
                panelGrille.add(b);
            }
        }

        // 3️⃣ Rafraîchissement
        panelGrille.revalidate();
        panelGrille.repaint();
        rafraichirGrille();
    }
    
    private void rafraichirGrille() {
        GrilleDeCellules g = partie.getGrille();

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                boolean etat = g.getCellule(i, j).getEtat();
                boutons[i][j].setBackground(
                        etat ? java.awt.Color.YELLOW : java.awt.Color.DARK_GRAY
                );
            }
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGrille = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGrille.setBackground(new java.awt.Color(0, 242, 0));

        javax.swing.GroupLayout panelGrilleLayout = new javax.swing.GroupLayout(panelGrille);
        panelGrille.setLayout(panelGrilleLayout);
        panelGrilleLayout.setHorizontalGroup(
            panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        panelGrilleLayout.setVerticalGroup(
            panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 242));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(242, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGrille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetrePrincipale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelGrille;
    // End of variables declaration//GEN-END:variables
}
