/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp_cadenas;

/**
 *
 * @author samar
 */
public class AffichageJeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AffichageJeu.class.getName());

    /**
     * Creates new form AffichageJeu
     */
    public AffichageJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Explication = new javax.swing.JLabel();
        CHIFFRE1 = new javax.swing.JLabel();
        CHIFFRE2 = new javax.swing.JLabel();
        CHIFFRE3 = new javax.swing.JLabel();
        CHIFFRE4 = new javax.swing.JLabel();
        NBRJUSTES = new javax.swing.JLabel();
        NBRHAUTS = new javax.swing.JLabel();
        NBRBAS = new javax.swing.JLabel();
        UP_BTN_1_ = new javax.swing.JButton();
        UP_BTN_2 = new javax.swing.JButton();
        UP_BTN_3 = new javax.swing.JButton();
        UP_BTN_4 = new javax.swing.JButton();
        DOWN_BTN_1 = new javax.swing.JButton();
        DOWN_BTN_2 = new javax.swing.JButton();
        DOWN_BTN_3 = new javax.swing.JButton();
        DOWN_BTN_4 = new javax.swing.JButton();
        Recommencer = new javax.swing.JButton();
        Essayer = new javax.swing.JButton();
        Tentatives = new javax.swing.JLabel();
        NBRSUR5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Explication.setText("Trouver le code du cadenas pour le deverouiller en moins de 5 essais!");
        getContentPane().add(Explication, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 15, 382, -1));

        CHIFFRE1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CHIFFRE1.setText("0");
        CHIFFRE1.setToolTipText("");
        CHIFFRE1.setAlignmentX(0.5F);
        getContentPane().add(CHIFFRE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 126, 40, 132));

        CHIFFRE2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CHIFFRE2.setText("0");
        CHIFFRE2.setAlignmentX(0.5F);
        getContentPane().add(CHIFFRE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 126, 40, 132));

        CHIFFRE3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CHIFFRE3.setText("0");
        CHIFFRE3.setAlignmentX(0.5F);
        getContentPane().add(CHIFFRE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 126, 40, 132));

        CHIFFRE4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CHIFFRE4.setText("0");
        CHIFFRE4.setAlignmentX(0.5F);
        getContentPane().add(CHIFFRE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 126, 40, 132));

        NBRJUSTES.setText("Nombre de chiffres justes:           0");
        getContentPane().add(NBRJUSTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 393, 185, -1));

        NBRHAUTS.setText("Nombre de chiffres trop hauts:   0 ");
        getContentPane().add(NBRHAUTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 415, -1, -1));

        NBRBAS.setText("Nombre de chiffres trop bas:      0 ");
        getContentPane().add(NBRBAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 440, -1, -1));

        UP_BTN_1_.setText("/\\");
            getContentPane().add(UP_BTN_1_, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 97, 40, -1));

            UP_BTN_2.setText("/\\");
                getContentPane().add(UP_BTN_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 97, 40, -1));

                UP_BTN_3.setText("/\\");
                    getContentPane().add(UP_BTN_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 97, 40, -1));

                    UP_BTN_4.setText("/\\");
                        getContentPane().add(UP_BTN_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 97, 40, -1));

                        DOWN_BTN_1.setText("\\/");
                        DOWN_BTN_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DOWN_BTN_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(DOWN_BTN_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 283, 40, -1));

                        DOWN_BTN_2.setText("\\/");
                        DOWN_BTN_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DOWN_BTN_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(DOWN_BTN_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 283, 40, -1));

                        DOWN_BTN_3.setText("\\/");
                        DOWN_BTN_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DOWN_BTN_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(DOWN_BTN_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 283, 40, -1));

                        DOWN_BTN_4.setText("\\/");
                        DOWN_BTN_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DOWN_BTN_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(DOWN_BTN_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 283, 40, -1));

                        Recommencer.setText("Recommencer");
                        getContentPane().add(Recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 437, -1, -1));

                        Essayer.setText("Essayer");
                        getContentPane().add(Essayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 188, -1, -1));

                        Tentatives.setText("Tentatives : ");
                        getContentPane().add(Tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 348, 72, -1));

                        NBRSUR5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                        NBRSUR5.setText("0/5 ");
                        getContentPane().add(NBRSUR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 370, 72, 51));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void DOWN_BTN_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWN_BTN_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWN_BTN_1ActionPerformed

    private void DOWN_BTN_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWN_BTN_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWN_BTN_2ActionPerformed

    private void DOWN_BTN_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWN_BTN_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWN_BTN_3ActionPerformed

    private void DOWN_BTN_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWN_BTN_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWN_BTN_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AffichageJeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CHIFFRE1;
    private javax.swing.JLabel CHIFFRE2;
    private javax.swing.JLabel CHIFFRE3;
    private javax.swing.JLabel CHIFFRE4;
    private javax.swing.JButton DOWN_BTN_1;
    private javax.swing.JButton DOWN_BTN_2;
    private javax.swing.JButton DOWN_BTN_3;
    private javax.swing.JButton DOWN_BTN_4;
    private javax.swing.JButton Essayer;
    private javax.swing.JLabel Explication;
    private javax.swing.JLabel NBRBAS;
    private javax.swing.JLabel NBRHAUTS;
    private javax.swing.JLabel NBRJUSTES;
    private javax.swing.JLabel NBRSUR5;
    private javax.swing.JButton Recommencer;
    private javax.swing.JLabel Tentatives;
    private javax.swing.JButton UP_BTN_1_;
    private javax.swing.JButton UP_BTN_2;
    private javax.swing.JButton UP_BTN_3;
    private javax.swing.JButton UP_BTN_4;
    // End of variables declaration//GEN-END:variables
}
